export const configuracoesTypes = {
  GET_CONFIGURACOES_REQUEST: 'GET_CONFIGURACOES_REQUEST',
  GET_CONFIGURACOES_SUCCESS: 'GET_CONFIGURACOES_SUCCESS',
  GET_CONFIGURACOES_FAILURE: 'GET_CONFIGURACOES_FAILURE',
};