export const inscricoesTypes = {
  GET_INSCRICOES_REQUEST: 'GET_INSCRICOES_REQUEST',
  GET_INSCRICOES_SUCCESS: 'GET_INSCRICOES_SUCCESS',
  GET_INSCRICOES_FAILURE: 'GET_INSCRICOES_FAILURE',
  GET_INSCRICAO_REQUEST: 'GET_INSCRICAO_REQUEST',
  GET_INSCRICAO_SUCCESS: 'GET_INSCRICAO_SUCCESS',
  GET_INSCRICAO_FAILURE: 'GET_INSCRICAO_FAILURE',
  GET_INSCRITOS_REQUEST: 'GET_INSCRITOS_REQUEST',
  GET_INSCRITOS_SUCCESS: 'GET_INSCRITOS_SUCCESS',
  GET_INSCRITOS_FAILURE: 'GET_INSCRITOS_FAILURE',
};