export const miscTypes = {
  GET_PAISES_REQUEST: 'GET_PAISES_REQUEST',
  GET_PAISES_SUCCESS: 'GET_PAISES_SUCCESS',
  GET_PAISES_FAILURE: 'GET_PAISES_FAILURE',

  GET_ESTADOS_REQUEST: 'GET_ESTADOS_REQUEST',
  GET_ESTADOS_SUCCESS: 'GET_ESTADOS_SUCCESS',
  GET_ESTADOS_FAILURE: 'GET_ESTADOS_FAILURE',

  GET_CIDADES_REQUEST: 'GET_CIDADES_REQUEST',
  GET_CIDADES_SUCCESS: 'GET_CIDADES_SUCCESS',
  GET_CIDADES_FAILURE: 'GET_CIDADES_FAILURE',
};