export const preinscricoesTypes = {
  GET_PREINSCRICOES_REQUEST: 'GET_PREINSCRICOES_REQUEST',
  GET_PREINSCRICOES_SUCCESS: 'GET_PREINSCRICOES_SUCCESS',
  GET_PREINSCRICOES_FAILURE: 'GET_PREINSCRICOES_FAILURE',
};