export const rankingTypes = {
  GET_RANKINGS_REQUEST: 'GET_RANKINGS_REQUEST',
  GET_RANKINGS_SUCCESS: 'GET_RANKINGS_SUCCESS',
  GET_RANKINGS_FAILURE: 'GET_RANKINGS_FAILURE',
  GET_RANKING_REQUEST: 'GET_RANKING_REQUEST',
  GET_RANKING_SUCCESS: 'GET_RANKING_SUCCESS',
  GET_RANKING_FAILURE: 'GET_RANKING_FAILURE',
};